### ISSUE TITLE
26일(수) 까지 version 2 마감입니다.

### ISSUE THREAD

**Issue by bnitech** [BBP-2017/CrashTower#2]
**[ version 2 의 각 브랜치별 구현해야하는 내용들입니다. ]**

## Battle @bnitech
- card를 mob으로 생성
- mob끼리(mob과 tower) 충돌처리
- tower 무너지면 종료

## Option @Rapha0814 
- sound on/off
- login data 저장
- option창 팝업으로 띄우기

## Mypage @Nor-op 
- 화면에 보여지는 Card list들을 Deck으로 옮겨서 표현
- Deck list 저장

## Multi @bnitech
- server 에 player 1과 player 2 의 정보 업로드
- player 1 과 player 2 매칭

## Result @bnitech
- Battle 종료시 player 정보 갱신
- 경과 화면 표시
- main 으로 이동

## Server @Rapha0814 
- server를 활용하기 위한 API 가져오기
- Game 내 데이터 server에 업로드
- server 내 데이터 Game에 다운로드

## Cards @Nor-op 
- player의 level에 따라 사용 가능한 card list 설정
- card list에서 card level 별 기본정보 갱

[ 자세한 내용은 아래 링크 참조 ]
[bnitech.tistory.com](http://bnitech.tistory.com/31)

**Comment by Nor-op** [comment]
갈길이 멀구만
